// archera-palette.ts — generated by Archera Palette Generator.
// Drop into _template/palettes/ and update the import in theme.ts to: './palettes/archera-palette'

export type TonalKey = 50 | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900;
export type TonalScale = Record<TonalKey, string>;
export interface ExtendedTonalScale extends TonalScale { A100: string; A200: string; A400: string; A700: string; }
export interface NeutralScale extends ExtendedTonalScale { white: string; black: string; }
export interface AppPalette {
  uiPrimary: TonalScale; brandPrimary: TonalScale;
  brandSecondary: TonalScale; brandTertiary: TonalScale;
  accent1: TonalScale; accent2: TonalScale;
  success: TonalScale; warning: TonalScale; error: TonalScale; info: TonalScale;
  neutral: NeutralScale;
  text: { primary: string; secondary: string; disabled: string; };
  background: string; surface: string; header: string;
}

const palette: AppPalette = {
  neutral: {
    "50": '#F7F7F7',
    "100": '#EEEEEF',
    "200": '#E1E1E2',
    "300": '#D0D0D1',
    "400": '#BFBFC1',
    "500": '#ABABAE',
    "600": '#97979A',
    "700": '#818185',
    "800": '#6B6B70',
    "900": '#57575C',
    "white": '#FFFFFF',
    "black": '#323234',
    "A100": '#F2F3F7',
    "A200": '#DADCE9',
    "A400": '#A9ADCC',
    "A700": '#5F659F',
  },
  uiPrimary: {
    "50": '#DEEEFB',
    "100": '#C5DBEE',
    "200": '#A4C3DD',
    "300": '#84ABCB',
    "400": '#6493BA',
    "500": '#4B82AD',
    "600": '#3176A7',
    "700": '#13699C',
    "800": '#1D567A',
    "900": '#0E3F5C',
  },
  brandPrimary: {
    "50": '#E6E1FF',
    "100": '#CFC6FF',
    "200": '#B2A0FF',
    "300": '#9879FF',
    "400": '#804AFF',
    "500": '#7101FF',
    "600": '#6900FF',
    "700": '#5F00F8',
    "800": '#4B00CB',
    "900": '#36009D',
  },
  brandSecondary: {
    "50": '#DEF9FF',
    "100": '#CDF4FF',
    "200": '#B6ECFF',
    "300": '#9DE5FF',
    "400": '#83DEFD',
    "500": '#6DD8FC',
    "600": '#3FC7EE',
    "700": '#00B3DB',
    "800": '#1E93B0',
    "900": '#076E85',
  },
  brandTertiary: {
    "50": '#FFE9E2',
    "100": '#FFDBD2',
    "200": '#FFC7BF',
    "300": '#FFB4AC',
    "400": '#FC9F9B',
    "500": '#F89090',
    "600": '#ED797D',
    "700": '#DB636A',
    "800": '#B1555C',
    "900": '#863D43',
  },
  accent1: {
    "50": '#FFF4DE',
    "100": '#FFEECF',
    "200": '#FFE6BB',
    "300": '#FFDEA6',
    "400": '#FFD691',
    "500": '#FFD080',
    "600": '#F0BA5C',
    "700": '#DDA239',
    "800": '#B4873D',
    "900": '#896429',
  },
  accent2: {
    "50": '#DDE5FF',
    "100": '#C1CCFF',
    "200": '#9DA9FD',
    "300": '#7C86F0',
    "400": '#5D62E1',
    "500": '#4A43D6',
    "600": '#402FD5',
    "700": '#3614CE',
    "800": '#2919A6',
    "900": '#1A0D80',
  },
  success: {
    "50": '#DAF0E6',
    "100": '#BEDDD0',
    "200": '#99C4B2',
    "300": '#73AC95',
    "400": '#4C9479',
    "500": '#2A8265',
    "600": '#007957',
    "700": '#006D49',
    "800": '#00583C',
    "900": '#004029',
  },
  warning: {
    "50": '#FFE5D4',
    "100": '#F8CEB7',
    "200": '#EAB092',
    "300": '#DC926E',
    "400": '#CC744B',
    "500": '#C05C2E',
    "600": '#B9480C',
    "700": '#AD3400',
    "800": '#8B2F02',
    "900": '#691F00',
  },
  error: {
    "50": '#FFE0D7',
    "100": '#F5C5BA',
    "200": '#E2A195',
    "300": '#CE7D72',
    "400": '#B95952',
    "500": '#A83C3C',
    "600": '#A2262E',
    "700": '#980922',
    "800": '#791320',
    "900": '#5B0716',
  },
  info: {
    "50": '#DCE9F8',
    "100": '#BED1E6',
    "200": '#97B2CE',
    "300": '#7293B6',
    "400": '#4D759E',
    "500": '#315F8C',
    "600": '#1A5689',
    "700": '#004B81',
    "800": '#093D64',
    "900": '#012C4B',
  },
  text: {
    primary:   '#57575C',
    secondary: '#97979A',
    disabled:  '#D0D0D1',
  },
  background: '#F6F5F4',
  surface:    '#FFFFFF',
  header:     '#170F57', // brand-accent-2/900 variant
};

export default palette;
